name: CI

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lint, Type Check & Audit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install-dependencies
        run: npm ci

      - name: check-vulnerabilities
        run: npm audit --audit-level=low

      - name: Lint
        run: npm run lint

      - name: Type-Check
        run: npm run type-check
