nname: Deploy to Staging

on:
  push:
    branches: [main]

env:
  PNPM_VERSION: '10.15.1'
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: pnpm build
      env:
        NODE_ENV: staging

    - name: Build Success
      run: |
        echo "✅ Build realizado com sucesso!"
        echo "📦 Commit: ${{ github.sha }}"
        echo "👤 Author: ${{ github.actor }}"